### ISSUE TITLE
error

### ISSUE THREAD

**Issue by masumipe** [amirsanni/conference-call-ratchet#1]
Uncaught SyntaxError: Unexpected reserved word in chat.js line 118

**Comment by amirsanni** [comment]
```
let answer = await pc[data.sender].createAnswer();
```

That's on line 118 in chat.js. Can you click on the error from the console to get the exact block?

**Comment by masumipe** [comment]
I am not that expert but tried to solve googling. here await is creating for not having async. I had an inefficient solution. You might need it with improvement :
 async function chq(e){
                                        let answer = await pc[data.sender].createAnswer();
                                        await pc[data.sender].setLocalDescription(answer);
                                        return answer;
                                    }
                                    chq(data).then((answer)=>{
                                        socket.send(JSON.stringify({
                                        action: 'sdp',
                                        description:pc[data.sender].localDescription, 
                                        to:data.sender, 
                                        sender:socketId,
                                        room: room
                                    }))
                                    });

**Comment by amirsanni** [comment]
Thanks. Will look into it.
