### ISSUE TITLE
when I am running server.php getting issue

### ISSUE THREAD

**Issue by paragikjain** [amirsanni/conference-call-ratchet#2]
`C:\xampp\htdocs\conference-call-ratchet>php Server.php
PHP Notice:  Trying to get property 'v' of non-object in C:\xampp\htdocs\conference-call-ratchet\Server.php on line 15

Notice: Trying to get property 'v' of non-object in C:\xampp\htdocs\conference-call-ratchet\Server.php on line 15
PHP Notice:  Trying to get property 'iceServers' of non-object in C:\xampp\htdocs\conference-call-ratchet\Server.php on line 15

Notice: Trying to get property 'iceServers' of non-object in C:\xampp\htdocs\conference-call-ratchet\Server.php on line 15
null`

**Comment by amirsanni** [comment]
What's the response from `Server.php`?

**Comment by amirsanni** [comment]
The xirsys account used has been deactivated by xirsys, hence why the error. Please create a free account there and use your credentials or better still, use an alternative provider.
