### ISSUE TITLE
Limit Users

### ISSUE THREAD

**Issue by seeguns** [amirsanni/conference-call-ratchet#4]
hello, How to limit user fo join room ??

**Comment by amirsanni** [comment]
You can do this in `ws/bin/amir/Comm.php`. In the `onMessage` method on line 66, add the following:

```
if(isset($this->rooms[$room]) && count($this->rooms[$room]) < USER_LIMIT){
    $this->rooms[$room][] = $from;//subscribe user to room
    $this->notifyUsersOfConnection($room, $from);
}
                
else{
    $msg_to_send = json_encode(['action'=>'room full']);
    $from->send($msg_to_send);
}
```

Replace **USER_LIMIT** with the maximum number of users you want to permit in a room.

**Note**: You can use any action here: `$msg_to_send = json_encode(['action'=>'room full']);`, just ensure you handle it well on the front-end.

**Comment by seeguns** [comment]
It's Works thanks

**Comment by amirsanni** [comment]
Welcome
